# Generated by Django 5.1.7 on 2025-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
        ('selected', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='selected.movie', verbose_name='Избранные'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
