# Generated by Django 5.1.7 on 2025-04-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_options_alter_user_table'),
        ('selected', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='selected.movie', verbose_name='Избранные'),
        ),
    ]
